{
    'name': 'Zain Provident Fund System',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Provident Fund Management – contributions, loans, withdrawals, land, resignation, and profit distribution',
    'author': 'OdooERP UAE',
    'depends': ['base', 'hr', 'account', 'mail', 'portal'],
    'data': [
        'security/zain_pfs_security.xml',
        'security/ir.model.access.csv',
        'data/zain_configuration_data.xml',
        'views/zain_member_views.xml',
        'views/zain_member_contribution_views.xml',
        'views/zain_loan_views.xml',
        'views/zain_withdrawal_views.xml',
        'views/zain_land_views.xml',
        'views/zain_land_loan_views.xml',
        'views/zain_resignation_views.xml',
        'views/zain_profit_distribution_views.xml',
        'views/zain_configuration_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
